language: R
warnings_are_errors: true

env:
  global:
    - CRAN: https://cran.rstudio.com
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

before_install:
before_install:
  - sudo apt-get install tcl-dev
  - sudo apt-get install tk-dev
